name: add_theme
description: Define your own ThemeData
version: 0.4.0
homepage: https://github.com/SuperPenguin/add_theme
repository: https://github.com/SuperPenguin/add_theme
issue_tracker: https://github.com/SuperPenguin/add_theme/issues

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=2.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0
