name: add_theme
description: Class and Widgets to help you define your own ThemeData and use it like Theme does
version: 0.4.2
homepage: https://github.com/SuperPenguin/add_theme
repository: https://github.com/SuperPenguin/add_theme
issue_tracker: https://github.com/SuperPenguin/add_theme/issues

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=2.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0
